---
title: "Assignment_4"
author: "Amy West"
date: '2022-10-05'
output: html_document
---
Some preliminary code
```{r, message=FALSE, warning=FALSE}
#load the necessary library packages
library (dplyr)
library(tidyverse)

#import ebird data into R
Toomey_ebird<-read.csv("~/Documents/School/Biol7263/WestBIOL7263/assignments/assn_4/MBT_ebird.csv")
head (Toomey_ebird)
```

**Problem 1:**

```{r}
year_count<-Toomey_ebird %>% #reference which file to count data in
  group_by(year) %>% #group data by year
  summarize(total=sum(count)) #add the count data and give the total for each year
```

the most birds were observed in 2014 and 9303 birds were observed

**Problem 2:**
```{r}
Species_2014<-Toomey_ebird %>% #create a data frame with information from the ebird file
  filter(year == 2014) %>% #only use birds from 2014
  count(common_name)  #list all the common names of birds 

nrow(Species_2014) #list the number of rows in the above data frame
```
A total of 210 species were observed in 2014

**Problem 3:**

```{r}
RWBL<-Toomey_ebird %>% #create a data frame with information from the ebird file
  filter(common_name == "Red-winged Blackbird") %>% #only use birds from 2014
  count(location, sort = TRUE) 
```
Birds were most commonly observed in Missouri

**Problem 4:**

```{r}
time_filter<-Toomey_ebird %>%#create a data frame with information from the ebird file
  filter(duration > 5) %>% #in the data frame put only birds with a duration greater than 5
  filter(duration<200)#in the data frame put only birds with a duration less than 200
 
species_day<-time_filter%>% #create a data frame with information from filtered file we just created
  group_by(year,date)%>% #group by year and date, the year is redundant but we will need that information for later
  count(common_name) #list the species observed on each day

options(dplyr.summarise.inform = FALSE)#some code to make sure the summarize command is counting the smaller group

species_perday<-species_day%>% #create a data frame with information from filtered file we just created
  group_by(year,date)%>% #group by year and date, the year is redundant but we will need that information for later
  summarise(species_per_day=n()) #count the number of rows for each day, which is equal to the number of species

duration_perday<-time_filter%>% #create a data frame with information from grouped file 
  group_by(year,date)%>% #group by year and date, the year is redundant but we will need that information for later
  summarise(duration=mean(duration)) #give the average duration of time for each day, which bears the question did Dr.Toomey ever have more than one checklist per day?

duration_year<-merge(duration_perday,species_perday) #merge the checklists with the species per day and duration per day
duration_year$species_per_min<-duration_year$species_per_day/duration_year$duration #add a variable to the merged checklist that divides species by duration

duration_year%>%  # use the data frame we jsut created
  group_by(year) %>% # group the dataframe by year
  summarise(average_species_per_minute= mean(species_per_min)) #take an average of the mean species per minute for each year
```

**Problem 5:**
```{r, warning=FALSE}
top_10<-Toomey_ebird%>% #create a new data frame and reference which data frame you're creating it from
  count (common_name)%>% #count the occurrence of each common name
  arrange(by=(desc(n))) #sort by the count from greatest to least
top_10_list<-as.list(top_10$common_name[1:10]) #create a list from the top 10 birds 

top_10_tibble<- as_tibble(Toomey_ebird%>% #create a tibble
  filter(common_name==top_10_list)) #filter based off the species in the list

#write tibble to a .csv
write_csv(top_10_tibble, "~/Documents/School/Biol7263/WestBIOL7263/assignments/assn_4/results/Toomey_top_10.csv")

head(top_10_tibble)
```
Link to download final file:

[Toomey_top_10](results/Toomey_top_10.csv)


**Link to script**

[Assignment 4](Assn_4_script.R)

